config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#new"
  devise_for :users
  resources :users
  resources :visitors
  resources :events
  post "/seats" => 'seats#reserve_seat'
  post "/seats/cancel" => 'seats#cancel_reservation'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :seats
  has_and_belongs_to_many :attendees, join_table: "seats", class_name: "User"

  def seat_rows(row_length=3)
  	seats.each_slice(row_length)
  end

  def available_seats
  	seats.select(&:available?)
  end

  def create_seats(seat_count)
  	new_seats = []
  	event_id = self.id
  	seat_count.times do |counter|
  		new_seats << Seat.new(event_id: event_id, seat_number: (counter + 1))
  	end
  	self.seats = new_seats
  end

  def attendees_seat(user_id)
    self.seats.find_by_user_id(user_id)
  end
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  def attendee
  	self.user
  end

  def taken?
  	self.attendee ? true : false
  end

  def available?
  	!taken?
  end

  def cancel_reservation
    self.user_id = nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_events, class_name: "Event",
                            foreign_key: "creator_id"
  has_many :seats
  has_and_belongs_to_many :attended_event, join_table: "seats", class_name: "Event"

  def name
    [self.first_name, self.last_name].compact.join(' ')
  end

  def current_seat(event_id)
    seats.where(event_id: event_id, user_id: current_user.id).first
  end

  def has_credits?
    credit > 0
  end

  def can_create_events?
    create_privileges
  end

  def deduct_credit
    self.credit -= 1
    self.save
  end

  def add_credit
    self.credit += 1
    self.save
  end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::API.new(Rails.application.secrets.mailchimp_api_key)
    result = mailchimp.lists.subscribe({
      :id => Rails.application.secrets.mailchimp_list_id,
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
    
#     connection = GoogleDrive.login(Rails.application.secrets.email_provider_username, Rails.application.secrets.email_provider_password
# )
#     ss = connection.spreadsheet_by_title('Third-Degree')
#     if ss.nil?
#       ss = connection.create_spreadsheet('Third-Degree')
#     end
#     ws = ss.worksheets[0]
#     last_row = 1 + ws.num_rows
#     ws[last_row, 1] = Time.new

#     ws[last_row, 3] = self.email

#     ws.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :gender << :age << :shoesize << :credit
    devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :gender << :age << :shoesize << :credit
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @seat_rows = @event.seat_rows
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    # if current_user.can_create_events?
      @event = Event.new(event_params)
      current_user.created_events << @event
      @event.create_seats(params[:seat_count].to_i)
      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    # end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.permit(:name, :datetime, :description)
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  def reserve_seat
  	@seat = Seat.find(params["seat_id"])
  	@prev_seat = Seat.where(event_id: params["event_id"],
  		                     user_id: current_user.id).first
  	if @prev_seat
  		@prev_seat.update(user_id: nil)
      @seat.update(user_id: current_user.id)
  	else
  		if current_user.has_credits?
        current_user.deduct_credit
        @seat.update(user_id: current_user.id)
      end
  	end
  	redirect_to event_path(@seat.event)
  end

  def cancel_reservation
    @event = Event.find(params["event_id"])
    if @seat = @event.attendees_seat(current_user.id)
      @seat.cancel_reservation
      current_user.add_credit
      @seat.save
      current_user.save
    end
    redirect_to event_path(@event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  # def index
  # 	@visitor = Visitor.new
  # end

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Got it, #{@visitor.email}."
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	Event name: <input type="text" name="name">
    When: <input type="datetime-local" name="datetime">
    Number of Seats: <input type="number" name="seat_count" min="1" max="100">
    Event description: <input id="event_desc" type="textarea" name="description">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event Name</th>
      <th>Available Seats</th>
      <th colspan="2">Modify event</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to "#{event.available_seats.count} available seats", event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<h1><%= @event.name %></h1>
<h2><%= @event.datetime %></h2>

Select a seat to buy or change: 
<form action="/seats" method="post">
  <select name="seat_id">
    <option value="" selected="selected">Available seats</option>
    <% @event.available_seats.each do |as| %>
      <option value="<%= as.id %>">seat #<%= as.seat_number %></option>
    <% end %>
  </select>
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <input type="hidden" name="event_id" value="<%= @event.id %>">
  <input type="submit" value="buy/change seat">
</form>

<form action="/seats/cancel" method="post">
  <input type="hidden" name="event_id" value="<%= @event.id %>">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <input type="submit" value="cancel reservation">
</form>

<div id="seating_chart">
  <% @seat_rows.each do |seat_row| %>
    <% seat_row.each do |seat| %> 
      <div id="<%= seat.id %>"class="seat <%= "taken" if seat.taken? %>">
        seat #<%= seat.seat_number %><br/>
        <%= seat.taken? ? seat.attendee.name : "available" %>
      </div>
    <% end %>
    <br>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Events', events_path %></li>
<% end %>
<% if user_signed_in? && current_user.can_create_events? %>
  <li><%= link_to 'Create event', new_event_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TDF" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= user.name %></td>
<td><%= link_to user.email, user %></td>
<td>Created At: <%= user.created_at %></td>
<td>Updated At: <%= user.updated_at %></td>
<td>Sign In Count: <%= user.sign_in_count %></td>
<td>Last Sign In: <%= user.last_sign_in_at %></td>
<td>Current Sign In IP: <%= user.current_sign_in_ip %></td>
<td>Credits Available: <%= user.credit %></td>
<td>Can Create Events: <%= user.create_privileges %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Created At: <%= @user.created_at if @user.created_at %></p>
<p>Updated At: <%= @user.updated_at if @user.updated_at %></p>
<p>Sign In Count: <%= @user.sign_in_count if @user.sign_in_count %></p>
<p>Last Sign In: <%= @user.last_sign_in_at if @user.last_sign_in_at %></p>
<p>Current Sign In IP: <%= @user.current_sign_in_ip if @user.current_sign_in_ip %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/visitors/new.html.erb
<h3>Welcome Friend</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>
<section>
  <div class="column">
    <h3>Subscribe to our newsletter by leaving your email!</h3>
  </div>
  <div class="column">
    <div class="form-centered">
      <%= simple_form_for @visitor do |f| %>
        <%= f.error_notification %>
        <%= f.input :email, label: false, :placeholder => 'Your Email' %>
        <br/>
        <%= f.button :submit, "Click Here to Send", :class => "submit" %>
      <% end %>
    </div>
  </div>
</section>